---
- name: Cisco Manual SSH Portal 
  hosts: switches
  gather_facts: no
  connection: network_cli
  vars:
    ansible_network_os: cisco.ios.ios
    # The commands you enter in the AWX Survey
    manual_ssh_input: ""

  tasks:
    - name: Execute CLI Commands
      cisco.ios.ios_command:
        commands: 
          - terminal length 0
          # We join all your lines into a list for the module
          - "{{ manual_ssh_input.split('\n') | select('regex', '\\S') | list }}"
      register: raw_output
      when: manual_ssh_input | trim | length > 0

    - name: View Raw Console Output
      ansible.builtin.debug:
        msg: "{{ item }}"
      loop: "{{ raw_output.stdout_lines | flatten }}"
      when: raw_output.stdout_lines is defined
