---
- name: Get hostname from Cisco switch
  hosts: switches
  gather_facts: no
  connection: network_cli
  vars:
    ansible_network_os: cisco.ios.ios

  tasks:
    - name: Run show version
      ios_command:
        commands:
          - show running-config | include username
      register: output

    - name: Display hostname
      debug:
        msg: "{{ output.stdout[0] }}"
